services:
    web:
        build:
          dockerfile: Dockerfile
        ports:
        - "8081:8081"
        volumes:
        - .:/app
        depends_on:
        - db
        - redis
    db:
        image: mysql@latest
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=delivery_demo_db
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_HOST=%
        - MYSQL_ROOT_USER=root
        ports:
        - "3306:3306"
        volumes:
        - ./mysql:/var/lib/mysql
    redis:
        image: redis@latest
        ports:
        - "6379:6379"