version: "3.8"
services:
    delivery-tracker:
        image: "delivery-tracker"
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "delivery-tracker"
        ports:
            - "8081:8081"
        env_file:
            -   .env
        depends_on:
            -   mysql
            -   redis
    mysql:
        image: "mysql:8.0"
        container_name: "mysql"
        ports:
            - "3306:3306"
        env_file:
            -   .env
        volumes:
            - ./mysql:/var/lib/mysql

    redis:
        image: "redis:latest"
        container_name: "redis"
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/data